### ISSUE TITLE
Proposal for sigma decay

### ISSUE THREAD

**Issue by mcoot** [tribesonecommunity/discord-bots#86]
Figured it might be worth writing an issue describing how we should implement a sigma decay feature

(Work in progress)

## Problem and background

Over time, as people play more games, Trueskill becomes more certain about their skill, reducing σ. If a player does not play for an extended period, their existing rating may become less relevant for any number of reasons (the player getting 'rusty', meta shifting) which should correspond to an increase in uncertainty about their skill, i.e. higher σ.

A common means of implementing this in skill rating systems like Trueskill is to apply some small, negative delta value to player uncertainty (σ) on an interval when they do not play, up to a maximum of the initial new player σ. (e.g. [OpenSkill supports this](https://openskill.me/en/stable/faq.html#does-this-library-support-time-decay)). This means that if a player does not play for a very extended period, the system will not change its understanding of their mean predicted skill (μ) but will become as uncertain about their skill as it is about a totally new player.

## Requirements

* The decay feature should be optional (controlled by config)
* Amount of decay applied should be configurable
    * (Should decay frequency also be configurable?)
* The bot should, roughly speaking, reliably perform the decay configuration on a schedule, even if the bot is frequently restarted
    * In particular, it would be bad for the bot to 'skip' some players who should be decayed while decaying for others as this would be 'unfair'
* The decay action should not be applied to players who have played more recently than some critical threshold value
* The decay job execution should not cause performance issues or lockups if other bot functionality is being used at the same time 

## Proposed implementation and open issues

(WIP)
* Data needed to perform decay job is 'when did each player last play?'; since decay applied is a constant delta, the _history_ of decay does not matter for the job
    * Right now I believe this information requires joining FinishedGame against FinishedGamePlayer against Player (or PlayerCategoryTrueskill?)
    * Is this join going to be performant with game history and player count increases?
        * Intuition: player count probably not going to be a problem (would be a nice problem to have lol), but searching for the most recent finished game a player was in _could_ be an issue with long histories; could attach a last_played timestamp to the player model instead if required
* Is the discord.ext scheduled tasks feature reliable enough for long timespan (day+) jobs? Not very familiar with it. How does it handle the bot being restarted?
* Can/should we use the existing (manual) PlayerDecay model? This keeps a history of decays applied but does not seem strictly required, and would more or less form an event history which would grow continuously
* How often should sigma decay be applied (per day, or per week?)? And should this be configurable? What is a good default decay amount?
* Should decay be per-queue, or global?

**Comment by mcoot** [comment]
Some thoughts on answering those questions...

* Decay applying per queue or to the underlying player model I'm still not sure on
* For the data layer, I'm tending towards suggesting adding a last_game_completed_at field to the Player or PlayerCategoryTrueskill table (depending on the answer to the prior point).
    * This is a denormalisation of the data since the same info could be reconstructed based on the game history, but I think there is at least a risk that building that info on what is effectively a scan over all players and then for each a query over the game history would be non-performant
    * Additionally, this should be easy to set in app code at the time of a game completion, and the impact of inconsistency between the value in the player model and the actual game history is small (in the worst case it could lead to a single unnecessary sigma decay being applied, but so long as the decay delta is small this is unlikely to be a noticeable issue)
    * Doing it this way also significantly simplifies the data access query from a readability perspective
* On task scheduling, if we use the tasks helper and specify an absolute time (to e.g. run the decay job at a set UTC time), in theory that ought to be resilient to bot restarts so long as the bot isn't down at the scheduled time (although I haven't looked into its internal implementation so needs further verification). If we assume that the impact of _missing_ a decay event is not too bad, this is probably acceptable. Note that the recently-merged scheduling functionality already relies on these loops using long-interval relative time scheduling, I'm not sure if there are potential issues with that during bot restarts 
* I can't immediately see a good reason to use the PlayerDecay table here. It would be straightforward to do so but I'm not sure if there is a good reason to track this history
* Decay applying once a day at a small delta seems initially reasonable, with the caveat that I think we should have a grace period, i.e. no decay for some period of time (1wk? 2wks?) and constant daily decay after that, defaulting such that it would revert to the default value (i.e. 8.33 unless other parameters were changed) over the span of maybe 2 months.

**Comment by StephenBartos** [comment]
Openskill doesn't support any explicit mechanism for sigma decay. They just give a description of the implementation, which is to apply some increase in sigma every day after "being inactive". A discord.py task that runs each day, increasing the sigma of each player that has not played a game in that day (up to the default) is pretty trivial to implement -- the hard part is determining the appropriate delta for different communities. This would only have an effect on the leaderboard and not matchmaking _directly,_ however, returning players would fluctuate more in their rating updates -- which may complicate matchmaking _indirectly_.

**Comment by StephenBartos** [comment]
>Decay applying per queue or to the underlying player model I'm still not sure on

Per `PlayerCategoryTrueskill`

> could attach a last_played timestamp to the player model instead if required

I do like this approach, as it eliminates the need to join tables and compute each player's last played date. However, I'm not sure how much performance you gain from doing so.
> Is the discord.ext scheduled tasks feature reliable enough for long timespan (day+) jobs? Not very familiar with it. How does it handle the bot being restarted?

They are fairly reliable. On each restart of the bot, each task is started in `main.py`. You can configure tasks to run in intervals, or at specific times -- in this case, it would make sense to run the decay task during an off peak time for pugs which should be configurable. See [discord.py tasks](https://discordpy.readthedocs.io/en/stable/ext/tasks/index.html)
> I can't immediately see a good reason to use the PlayerDecay table here. It would be straightforward to do so but I'm not sure if there is a good reason to track this history

Agreed
> Decay applying once a day at a small delta seems initially reasonable, with the caveat that I think we should have a grace period, i.e. no decay for some period of time (1wk? 2wks?) and constant daily decay after that, defaulting such that it would revert to the default value (i.e. 8.33 unless other parameters were changed) over the span of maybe 2 months.
It depends on how large the delta is. If the delta is fairly small, meaning it would take (let's say) 100 days to reach the default sigma then I wouldn't mind it applying not having a grace period. However, if it were to take 1 month then I wouldn't.

**Comment by StephenBartos** [comment]
> The decay job execution should not cause performance issues or lockups if other bot functionality is being used at the same time

To add onto this, the most important time you do not want to update a player is after a game has finished, and each player's `PlayerCategoryTrueskill` row is being updated. Updating a player's sigma while a game is in progress alters how each player's mu/sigma changes after the game is finished.
The most simple rational would be that a player in a game is not inactive

**Comment by StephenBartos** [comment]
Feature implemented in #88 thank you!
